### ISSUE TITLE
error: fail to open "/model/model_15-symbol.json"

### ISSUE THREAD

**Issue by huwenhao1998** [haofanwang/mxnet-headpose#10]
mxnet.base.MXNetError: [19:43:04] G:\deeplearn\mxnet\dmlc-core\src\io\local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "/model/model_15-symbol.json"

**Comment by haofanwang** [comment]
Try "./model/model_15-symbol.json"
