### ISSUE TITLE
Check failed: p!= end Bad ImageList format

### ISSUE THREAD

**Issue by jensleeGit** [haofanwang/mxnet-headpose#3]
您好，请问一下，我使用im2rec.py将图片文件夹下的图片进行转化，最后生成.lst, .rec, .idx文件，用rec与idx对应输入的参数，但是还是报错，请问这是为什么？

I use im2rec.py to generate the .rec file and .idx file. 
Then use them as parameter link to the code ,but it's still wrong.

**Comment by haofanwang** [comment]
Hi, @jensleeGit , you may try to generate these files in two steps. First, generate .lst by hand (write into an empty .lst line by line), then, run im2rec.py using the generated .lst as an input param to generate .rec & .idx.

Note that only .lst & .rec are needed in our project. Good luck:D

**Comment by haofanwang** [comment]
Closed. If you have any further questions, feel free to open an new issue.

**Comment by jensleeGit** [comment]
sir, thank you for your help.




------------------ 原始邮件 ------------------
发件人: "Haofan Wang"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 上午8:49
收件人: "haofanwang/mxnet-Head-Pose"<mxnet-Head-Pose@noreply.github.com>; 
抄送: "李振"<913470452@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [haofanwang/mxnet-Head-Pose] Check failed: p!= end Bad ImageListformat (#3)




Closed #3.
