### ISSUE TITLE
test.py doesnot work

### ISSUE THREAD

**Issue by ailihong** [haofanwang/mxnet-headpose#4]
Hello,
   when i run python3 test.py --mode 1 --model_json model/model_15-symbol.json --model_params model/model_15-0000.params,I got the error message as follow:

/usr/local/lib/python3.5/dist-packages/mxnet/module/base_module.py:54: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
  warnings.warn(msg)
/usr/local/lib/python3.5/dist-packages/mxnet/module/base_module.py:66: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)

 is anyone konw how to fix it,thank you very much in advance.

**Comment by ailihong** [comment]
sorry,it working,I made some mistakes

**Comment by zjz19960805** [comment]
I meet the same problem, can you tell me how to fix it?

**Comment by ailihong** [comment]
@zjz19960805 
Actually,I didnot fix this issues,just ignore it.Maybe i didnot install some dependence like matplotlib.
